/* tslint:disable */
/* eslint-disable */
/**
 * Torrents Stream Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ProviderErrorModel } from './ProviderErrorModel'
import {
    ProviderErrorModelFromJSON,
    ProviderErrorModelFromJSONTyped,
    ProviderErrorModelToJSON,
} from './ProviderErrorModel'
import type { ProviderModel } from './ProviderModel'
import {
    ProviderModelFromJSON,
    ProviderModelFromJSONTyped,
    ProviderModelToJSON,
} from './ProviderModel'

/**
 *
 * @export
 * @interface GetProviders200Response
 */
export interface GetProviders200Response {
    /**
     *
     * @type {Array<ProviderModel>}
     * @memberof GetProviders200Response
     */
    items: Array<ProviderModel>
    /**
     *
     * @type {Array<ProviderErrorModel>}
     * @memberof GetProviders200Response
     */
    errors: Array<ProviderErrorModel>
}

/**
 * Check if a given object implements the GetProviders200Response interface.
 */
export function instanceOfGetProviders200Response(value: object): boolean {
    let isInstance = true
    isInstance = isInstance && 'items' in value
    isInstance = isInstance && 'errors' in value

    return isInstance
}

export function GetProviders200ResponseFromJSON(
    json: any
): GetProviders200Response {
    return GetProviders200ResponseFromJSONTyped(json, false)
}

export function GetProviders200ResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): GetProviders200Response {
    if (json === undefined || json === null) {
        return json
    }
    return {
        items: (json['items'] as Array<any>).map(ProviderModelFromJSON),
        errors: (json['errors'] as Array<any>).map(ProviderErrorModelFromJSON),
    }
}

export function GetProviders200ResponseToJSON(
    value?: GetProviders200Response | null
): any {
    if (value === undefined) {
        return undefined
    }
    if (value === null) {
        return null
    }
    return {
        items: (value.items as Array<any>).map(ProviderModelToJSON),
        errors: (value.errors as Array<any>).map(ProviderErrorModelToJSON),
    }
}
