/* tslint:disable */
/* eslint-disable */
/**
 * Torrents Stream Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ProviderCategoryModelSubcategoriesInner
 */
export interface ProviderCategoryModelSubcategoriesInner {
    /**
     *
     * @type {string}
     * @memberof ProviderCategoryModelSubcategoriesInner
     */
    name: string
    /**
     *
     * @type {string}
     * @memberof ProviderCategoryModelSubcategoriesInner
     */
    id: string
}

/**
 * Check if a given object implements the ProviderCategoryModelSubcategoriesInner interface.
 */
export function instanceOfProviderCategoryModelSubcategoriesInner(
    value: object
): boolean {
    let isInstance = true
    isInstance = isInstance && 'name' in value
    isInstance = isInstance && 'id' in value

    return isInstance
}

export function ProviderCategoryModelSubcategoriesInnerFromJSON(
    json: any
): ProviderCategoryModelSubcategoriesInner {
    return ProviderCategoryModelSubcategoriesInnerFromJSONTyped(json, false)
}

export function ProviderCategoryModelSubcategoriesInnerFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): ProviderCategoryModelSubcategoriesInner {
    if (json === undefined || json === null) {
        return json
    }
    return {
        name: json['name'],
        id: json['id'],
    }
}

export function ProviderCategoryModelSubcategoriesInnerToJSON(
    value?: ProviderCategoryModelSubcategoriesInner | null
): any {
    if (value === undefined) {
        return undefined
    }
    if (value === null) {
        return null
    }
    return {
        name: value.name,
        id: value.id,
    }
}
