/* tslint:disable */
/* eslint-disable */
/**
 * Torrents Stream Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { ApiErrorModel, Log, UsageModel } from '../models'
import {
    ApiErrorModelFromJSON,
    ApiErrorModelToJSON,
    LogFromJSON,
    LogToJSON,
    UsageModelFromJSON,
    UsageModelToJSON,
} from '../models'

/**
 *
 */
export class DashboardApi extends runtime.BaseAPI {
    /**
     * Retrieve latest server logs
     */
    async getLogsRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<Array<Log>>> {
        const queryParameters: any = {}

        const headerParameters: runtime.HTTPHeaders = {}

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken
            const tokenString = await token('apiKey', [])

            if (tokenString) {
                headerParameters['Authorization'] = `Bearer ${tokenString}`
            }
        }
        const response = await this.request(
            {
                path: `/api/logs`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        )

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            jsonValue.map(LogFromJSON)
        )
    }

    /**
     * Retrieve latest server logs
     */
    async getLogs(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<Array<Log>> {
        const response = await this.getLogsRaw(initOverrides)
        return await response.value()
    }

    /**
     */
    async getUsageRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<UsageModel>> {
        const queryParameters: any = {}

        const headerParameters: runtime.HTTPHeaders = {}

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken
            const tokenString = await token('apiKey', [])

            if (tokenString) {
                headerParameters['Authorization'] = `Bearer ${tokenString}`
            }
        }
        const response = await this.request(
            {
                path: `/api/usage`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        )

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            UsageModelFromJSON(jsonValue)
        )
    }

    /**
     */
    async getUsage(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<UsageModel> {
        const response = await this.getUsageRaw(initOverrides)
        return await response.value()
    }
}
